
--------------------------
=  test file array.test.cpp
=== run should_build_empty_array
===== at l.7 test arr.size() == 1 : [1m[32mOK[0m
===== at l.8 test arr.begin() == arr.data() : [1m[32mOK[0m
===== at l.9 test arr.end() == arr.begin() + arr.size() : [1m[32mOK[0m

--------------------------
=  test file array.test.cpp
=== run should_build_initialized_array
===== at l.15 test arr.size() == 2 : [1m[32mOK[0m
===== at l.16 test arr[0] == 1 : [1m[32mOK[0m
===== at l.17 test arr[1] == 2 : [1m[32mOK[0m
