name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install GCC11, pCap, wxWidgets
      run: sudo apt update && sudo apt install -y gcc-11 g++-11 
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Git Sumbodule Update
      run: |
        git pull --recurse-submodules
        git submodule update --remote --recursive
    - name: make clean
      run: make clean
    - name: make 
      run: make 
